/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finance;

import java.awt.event.*;//for closing a window when another opens
import java.awt.*;// same as line above

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;//for the defaultTableModel 
/**
 *
 * @author edgarcruz
 */
import java.io.*;//for expense button. new
import org.jfree.chart.ChartUtilities; // new
import org.jfree.data.general.DefaultPieDataset; //new

import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
public class moneyLeftoverPage extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;

    /**
     * Creates new form moneyLeftOverPage
     */
    DefaultTableModel model;
    public moneyLeftoverPage() {
        initComponents();
        model=(DefaultTableModel)totalIncomeTable.getModel();
        conn=javaConnect.ConnecrDb(); 
        Update_table();
        Update_table2();
    }
    //gets the data from net2 sqlite table
private void Update_table()
    {
    
        try
        {
            String sql = "select * from net2";//open the query connection to the database
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            totalIncomeTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }   
        //After the catch block you have to write this. 
        //When you write this after executing the query we are closing the connection. 
        //We're making it ready for the next connection.    
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e); //added 12/5/17
            }
        }
    } 
private void Update_table2()
    {
    
        try
        {
            String sql = "select * from spend2";//open the query connection to the database
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            totalExpenseTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }   
        //After the catch block you have to write this. 
        //When you write this after executing the query we are closing the connection. 
        //We're making it ready for the next connection.    
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e); //added 12/5/17
            }
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        totalIncomeTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        totalExpenseTable = new javax.swing.JTable();
        totalIncomeVariable = new javax.swing.JTextField();
        start = new javax.swing.JTextField();
        subtractButton = new java.awt.Button();
        moneyLeftover = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        expensePieChartButton = new java.awt.Button();
        button3 = new java.awt.Button();
        Delete = new java.awt.Button();
        DeleteExpenseRow = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(48, 58, 115));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Money Leftover");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("+");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Income Usage Statistics");

        button1.setBackground(new java.awt.Color(0, 204, 0));
        button1.setLabel("Home");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        totalIncomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "from", "to", "total income"
            }
        ));
        totalIncomeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalIncomeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(totalIncomeTable);

        totalExpenseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "from", "to", "total expense"
            }
        ));
        totalExpenseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalExpenseTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(totalExpenseTable);

        totalIncomeVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalIncomeVariableActionPerformed(evt);
            }
        });

        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        subtractButton.setBackground(new java.awt.Color(255, 255, 51));
        subtractButton.setLabel("Calculate");
        subtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractButtonActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Money Leftover $");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Please Select Total Income");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Please Select Total Expense");

        expensePieChartButton.setBackground(new java.awt.Color(255, 255, 51));
        expensePieChartButton.setLabel("Expense Pie Chart");
        expensePieChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensePieChartButtonActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(255, 255, 51));
        button3.setLabel("Edit Budget");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(255, 0, 0));
        Delete.setLabel("Delete Income Row ");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        DeleteExpenseRow.setBackground(new java.awt.Color(255, 0, 0));
        DeleteExpenseRow.setLabel("Delete Expense Row ");
        DeleteExpenseRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteExpenseRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(328, 328, 328)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(183, 183, 183)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(expensePieChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                                    .addGap(75, 75, 75)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalIncomeVariable)
                                    .addComponent(start)
                                    .addComponent(subtractButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(moneyLeftover)
                                    .addComponent(jLabel5)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteExpenseRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(totalIncomeVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteExpenseRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(subtractButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyLeftover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(expensePieChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void close() {
    WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        close ();
        new createDisplayPage().setVisible(true); // navigate to Home page
        
    }//GEN-LAST:event_button1ActionPerformed

    private void totalIncomeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalIncomeTableMouseClicked
         try{
            int row = totalIncomeTable.getSelectedRow();
            String Table_click=(totalIncomeTable.getModel().getValueAt(row, 0).toString());
            String sql = "select * from net2 where start = '"+Table_click+"' "; //first write the query
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()) {
                String add1 =rs.getString("totalIncome");        
                totalIncomeVariable.setText(add1);               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e); //added 12/5/17
            }
        }
    }//GEN-LAST:event_totalIncomeTableMouseClicked

    private void totalExpenseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalExpenseTableMouseClicked
        try{
            int row = totalExpenseTable.getSelectedRow();
            String Table_click=(totalExpenseTable.getModel().getValueAt(row, 0).toString());
            String sql = "select * from spend2 where start = '"+Table_click+"' "; //first write the query
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()) {
                String add1 =rs.getString("totalExpense");        
                start.setText(add1);               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e); //added 12/5/17
            }
        }
    }//GEN-LAST:event_totalExpenseTableMouseClicked

    private void subtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractButtonActionPerformed
         int num1,num2,sub;
        num1=Integer.parseInt(totalIncomeVariable.getText());
        num2=Integer.parseInt(start.getText());
        sub=num1-num2;
        moneyLeftover.setText(" "+sub);
    }//GEN-LAST:event_subtractButtonActionPerformed

    private void expensePieChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensePieChartButtonActionPerformed
       try
       {
            DefaultPieDataset dataset = new DefaultPieDataset( );
      
            String sql= "select * from expenses";//query
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            while(rs.next()) 
            {
                 dataset.setValue( 
                 rs.getString( "expenseType" ) ,
                 Integer.parseInt( rs.getString("amount")));
            }
            JFreeChart chart= ChartFactory.createPieChart("Expense Pie Chart", dataset, true, true, true);
            PiePlot P=(PiePlot)chart.getPlot();
            ChartFrame frame =new ChartFrame("Expense Pie Chart", chart);
            frame.setVisible(true);
            frame.setSize(450,500); 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }   
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e); //added 12/5/17
            }
        }
       
        
        /*
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("One", new Integer(10));
        pieDataset.setValue("Two", new Integer(20));
        pieDataset.setValue("Three", new Integer(30));
        pieDataset.setValue("Four", new Integer(40));   
        JFreeChart chart= ChartFactory.createPieChart("Expense Pie Chart", pieDataset, true, true, true);
        PiePlot P=(PiePlot)chart.getPlot();
        //P.setForegroundAplha(TOP_ALIGNMENT);
        ChartFrame frame =new ChartFrame("Expense Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(450,500);
        */
    }//GEN-LAST:event_expensePieChartButtonActionPerformed

    private void totalIncomeVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalIncomeVariableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalIncomeVariableActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
 close();
        new addIncomesPages().setVisible(true);

    }//GEN-LAST:event_button3ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        String sql="delete from net2 where totalIncome =?";//tried it with rowid, start and it didn't delete. I even changed the 
        //variable name from totalIncomeVariable to start (when i chose start). Didn't work. It seems like it 
            //doesn't like deleting the dates. 
        try
        {
           pst=conn.prepareStatement(sql);
           pst.setString(1,totalIncomeVariable.getText());
           pst.execute();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e); //added 12/5/17
            }
        }
        Update_table(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void DeleteExpenseRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteExpenseRowActionPerformed
           String sql="delete from spend2 where totalExpense =?";//tried it with rowid, start and it didn't delete. I even changed the 
        //variable name from totalIncomeVariable to start (when i chose start). Didn't work. It seems like it 
            //doesn't like deleting the dates. 
        try
        {
           pst=conn.prepareStatement(sql);
           pst.setString(1,start.getText());
           pst.execute();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try
            {
                rs.close();
                pst.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e); //added 12/5/17
            }
        }
        Update_table2();
    }//GEN-LAST:event_DeleteExpenseRowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moneyLeftoverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moneyLeftoverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moneyLeftoverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moneyLeftoverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moneyLeftoverPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Delete;
    private java.awt.Button DeleteExpenseRow;
    private java.awt.Button button1;
    private java.awt.Button button3;
    private java.awt.Button expensePieChartButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField moneyLeftover;
    private javax.swing.JTextField start;
    private java.awt.Button subtractButton;
    private javax.swing.JTable totalExpenseTable;
    private javax.swing.JTable totalIncomeTable;
    private javax.swing.JTextField totalIncomeVariable;
    // End of variables declaration//GEN-END:variables
}
